### PR TITLE
Add code coverage to tox run

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
@martinpitt Might be interesting inspiration for #13

### CODE REVIEW

**Comment by martinpitt** [comment]
@allisonkarlitskaya : If you prefer that approach, I can do that for pyflakes as well. I must say, it's against what *I* want to do, given the sorry state of the python stack in rawhide (e.g. https://bugzilla.redhat.com/show_bug.cgi?id=2101222) - and tox won't help with that, as current pylint/astroid is just incompatible with py3.11 so far.

That's the conceptual difficulty that I have with tox and venv: Either you go *all the way* and install some kind of distro-agnostic python interpreter as well, or you go all the way and use pure distro packages (which at least in Fedora and Ubuntu stable are compatible with each other and consistent). This current mix and match between "latest pip" and "current distro" has broken for me too often.

**Comment by allisonkarlitskaya** [comment]
@martinpitt so then, the first commit, but not the second one?

I have to admit that I'm spending the last days with this stuff trying to develop a sense of taste for what the right thing to do here is.  I know that I actually don't care at all about the testing frameworks, and as for the library itself, it depends on exactly one thing (`libsystemd`) which is always going to be installed on the system that we're testing.

If you've had enough trouble with the virtual env approach to favour manually maintaining the testing dependencies on all of the different systems we want to test on, then I'm happy to let you do that. :)

**Comment by allisonkarlitskaya** [comment]
@martinpitt what's your take on https://pypi.org/project/tox-current-env/ ?

**Comment by martinpitt** [comment]
@allisonkarlitskaya : I don't have any kind of authoritative opinion, TBH, just some preference towards distro packages. Feel free to experiment of course. IMO tests should happen against the distro runtime dependencies, but for things like pylint or pyflakes (test-only static code checkers) it does not matter that much in the end.

I do like the idea of having some kind of central scripts location like `$tool check` which would invoke the unit tests, pylint, pyflakes, etc. tox seems to provide that. I also saw some ["scripts" section in pyproject.toml](https://discuss.python.org/t/a-new-pep-to-specify-dev-scripts-and-or-dev-scripts-providers-in-pyproject-toml/11457), but I'm not sure how well that is implemented. I actually like that in our `package.json`, where you can just do `npm run eslint:fix` and such. But if that's not well supported yet, then let's use tox (i.e. your first commit).

**Pull request merged**
