### PR TITLE
Add PathWatch unit tests

### PR DESCRIPTION
**Pull request by martinpitt**

### CODE REVIEW

**Comment by martinpitt** [comment]
Interesting [C8S only failure](https://github.com/allisonkarlitskaya/systemd_ctypes/runs/7090255548?check_suite_focus=true) on my [previous commit](https://github.com/allisonkarlitskaya/systemd_ctypes/commit/a51e9ad700310f6f3d361a2367e4e45e240c3e7b). Let's see if that happens again.

**Comment by martinpitt** [comment]
... yep, it does. Even though gh seems to refuse to show the results in this PR, my fork's actions has it. [failure log](https://github.com/martinpitt/systemd_ctypes/runs/7090368233?check_suite_focus=true)

**Comment by martinpitt** [comment]
I skipped the root directory identity test on RHEL/CentOS 8 for now, to avoid the assertion crash.

**Comment by martinpitt** [comment]
@allisonkarlitskaya : Ready for review now

**Review by allisonkarlitskaya — APPROVED** [review]
Thank you very much!

**Pull request merged**
